[package]
name = "cairo-recursion-gvn"
version = "0.1.0"
edition = "2021"

[dependencies]
stwo-prover.workspace = true
num-traits.workspace = true
serde.workspace = true
bincode.workspace = true

[[bin]]
name = "export-to-file"
test = false
harness = false